### PR TITLE
Rename Factory(Girl->Bot)

### PR DESCRIPTION
**Pull request by tjallingvanderwal**
They decided to change their name to FactoryBot.

* [Blog post](https://robots.thoughtbot.com/factory_bot)
* [Repo](https://github.com/thoughtbot/factory_bot)
* [UPGRADE_FROM_FACTORY_GIRL.md](https://github.com/thoughtbot/factory_bot/blob/48296b93765cffc71169e712e6a75e03119e32b7/UPGRADE_FROM_FACTORY_GIRL.md)

### CODE REVIEW

**Comment by tjallingvanderwal** [comment]
3 out of 4 Travis jobs fail with this error during setup:

```
$ gem uninstall bundler -x -I
ERROR:  While executing gem ... (Gem::InstallError)
    bundler is not installed in GEM_HOME, try:
	gem uninstall -i /home/travis/.rvm/gems/ruby-2.3.3@global bundler
The command "gem uninstall bundler -x -I" failed and exited with 1 during .
```

Only the 1.8.7 job succeeds.

Is there something I can fix? I'm kinda reluctant to experiment with your `.travis.yml`.

**Comment by kratob** [comment]
Thanks for the PR!

You're right not to touch our `.travis.yml` :-) I'll try to get it working again.

**Comment by triskweline** [comment]
Thanks for not breaking old apps that are still using `factory_girl` :)

**Comment by kratob** [comment]
Released as 1.11.8.

**Pull request merged**
